# Generated by Django 4.0 on 2021-12-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_content',
            field=models.TextField(default=''),
        ),
    ]
